### ISSUE TITLE
[BUG] support google cloud storage path in hugeCTR backend

### ISSUE THREAD

**Issue by mengdong** [triton-inference-server/hugectr_backend#21]
When serving models in cloud, users typically leverage a cloud storage path like gs://GCS_bucket/models/deepfm/1/deepfm0_sparse_0.model

For example, the config.pbtxt will contains
```
parameters {
  key: "config"
  value {
    string_value: "gs://[bucket_name]/models/deepfm/1/deepfm.json"
  }
}
```

Current hugeCTR backend will report `I1030 21:59:03.044715 167 hugectr.cc:282] Fail to open Parameter Server Configuration, please check whether the file path is correct`

**Comment by yingcanw** [comment]
Sorry for the late rely. Currently HugeCTR Backend only supports reading model files and configuration files from the local disk to initialize the PS. In later versions, we will gradually support reading configuration files and model files from kafka and the cloud.

**Comment by mengdong** [comment]
Adding @sohn21c could we track this as a new feature request?
