### ISSUE TITLE
The  max_batch_size configuration not work in batching inference?

### ISSUE THREAD

**Issue by offbye** [triton-inference-server/hugectr_backend#26]
I have  changed the "max_batch_size" in ps.json and  /model/wdl/config.pbtxt,   configured   64 , 256, 1024 and 4096 , and make pressure test with 100 http client， and  check log， found  inference  batch  not change,  the reponse time  also  samilar  in different   max_batch_size configuration.

Is  max_batch_size configure available in hugectr_backend ?    Any  suggestion  about the value and function of  max_batch_size?

**Comment by yingcanw** [comment]
The max_batch_size parameter indicates the maximum number of samples in each request. If 100 independent requests are sent to the triton server, then each batch is still 1 and will not be packed into 100.

**Comment by offbye** [comment]
Ok, got it

**Comment by offbye** [comment]
Ok, got it
