### ISSUE TITLE
Inconsistency between hugeCTR v3.3.1 and hugectr_backend v3.3.1

### ISSUE THREAD

**Issue by dfisk** [triton-inference-server/hugectr_backend#31]
Hi Folks,

I just tried building the latest tags from scratch and hugectr_backend fails with three issues:

1. Use of \<filesystem\> requires c++std17
2. It looks like hugectr_backend anticipates the need for {db_type, redis_ip, rocksdb_path, cache_size_percentage_redis} to kept in HugeCTR::InferenceParams but they are nowhere used at present; either add the members or hold off on the assignments until they are needed.
3. Warning as fatal error; variable assigned and not used "float cache_size_percentage_redis=0.1

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 215b520..479dd2d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -99,7 +99,7 @@ target_include_directories(
     ${CMAKE_CURRENT_SOURCE_DIR}/src
 )

-target_compile_features(triton-hugectr-backend PRIVATE cxx_std_11)
+target_compile_features(triton-hugectr-backend PRIVATE cxx_std_17)
 target_compile_options(
   triton-hugectr-backend PRIVATE
   $<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>,$<CXX_COMPILER_ID:GNU>>:
diff --git a/src/hugectr.cc b/src/hugectr.cc
index 2979c85..629259a 100644
--- a/src/hugectr.cc
+++ b/src/hugectr.cc
@@ -298,7 +298,7 @@ HugeCTRBackend::ParseParameterServer(const std::string& path){
   LOG_MESSAGE(TRITONSERVER_LOG_INFO,(std::string("The depolyment Data base type is: ") + db_type).c_str());

   float cache_size_percentage_redis=0.1;
-  std::string cpu_cache_per;
+  std::string cpu_cache_per = std::to_string(cache_size_percentage_redis);
   parameter_server_config.MemberAsString("cache_size_percentage_redis", &cpu_cache_per);
   cache_size_percentage_redis=std::atof(cpu_cache_per.c_str());
   LOG_MESSAGE(TRITONSERVER_LOG_INFO,(std::string("The depolyment cache_size_percentage_redis is: ") + cpu_cache_per).c_str());
@@ -340,6 +340,7 @@ HugeCTRBackend::ParseParameterServer(const std::string& path){
     }

     HugeCTR::InferenceParams infer_param(modelname, 64, 0.55, dense, sparses, 0, true, 0.55, support_int64_key_);
+    /*
     if(db_type== "local"){
       infer_param.db_type=HugeCTR::DATABASE_TYPE::LOCAL;
     }
@@ -353,6 +354,7 @@ HugeCTRBackend::ParseParameterServer(const std::string& path){
     infer_param.redis_ip =redis_ip;
     infer_param.rocksdb_path = rocksdb_path;
     infer_param.cache_size_percentage_redis = cache_size_percentage_redis;
+     */
     inference_params_map.insert(std::pair<std::string, HugeCTR::InferenceParams>(modelname, infer_param));
   }
   return nullptr;
```

**Comment by yingcanw** [comment]
Thanks for your feedback. In order to better solve the problem you encountered, could you provide the docker image info you used for building (it should work on the latest version nvcr.io/nvidia/merlin/merlin-inference:22.01 ) and specific building errors?

**Comment by dfisk** [comment]
Hi, sorry for the delayed response, just checking on this...
I ran into these build issues starting with container nvcr.io/nvidia/tritonserver:21.12-tf2-python-py3
The actual build errors that led to the work arounds in the above diff were (in order of occurrence in the diff):
1)```In file included from /usr/include/inference/embedding_interface.hpp:20,
                 from /usr/include/inference/hugectrmodel.hpp:21,
                 from /repos/hugectr_inference_backend/src/hugectr.cc:39:
/usr/include/inference/inference_utils.hpp:168:59: error: 'std::filesystem' has not been declared
  168 |                            const std::string& path = std::filesystem::temp_directory_path() /
      |                                                           ^~~~~~~~~~```
2) ```A warning as error on std::string cpu_cache_per declared but unused```
3) ```/repos/hugectr_inference_backend/src/hugectr.cc:344:19: error: 'struct HugeCTR::InferenceParams' has no member named 'db_type'
  344 |       infer_param.db_type=HugeCTR::DATABASE_TYPE::LOCAL;
      |                   ^~~~~~~``` 

Thanks

**Comment by yingcanw** [comment]
@dfisk Thanks for your info.  Merlin maintains docker images for each released at [NGC ](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-inference)(nvcr.io/nvidia/merlin/merlin-inference:22.01 is the container that matches v3.3.1). So if you need to build HugeCTR and HugeCTR Backend from the scratch, you can refer to the documentations or docker file (https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/dockerfile.tri#L209-L228) 
 I also tried to reproduce your issue in merlin-inference:22.01 (v100)  following the steps below, but all compilations were successful：
 
```
git clone  https://github.com/NVIDIA-Merlin/HugeCTR.git hugectr_github
cd hugectr_github
git checkout v3.3.1
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DSM="70" -DENABLE_INFERENCE=ON ..
make -j64  install

git clone https://github.com/triton-inference-server/hugectr_backend.git
cd hugectr_backend
git checkout v3.3.1
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/hugectr -DTRITON_COMMON_REPO_TAG=r21.12 -DTRITON_CORE_REPO_TAG=r21.12 -DTRITON_BACKEND_REPO_TAG=r21.12 ..
make -j64

```

**Comment by dfisk** [comment]
@yingcanw The errors I encountered are more likely related to the cmake macro arguments for hugectr_backend ; in fact I am pretty sure at least one of those variables in my case called for a r21.11 so this is the primary suspect.  How does one know the correct macro versions required for a given tag on checkout, let alone the correct version of any/all depended include files in external components ?  I was hitting inconsistencies between the above two repositories with the same tag. I will try to pinpoint the cause of my error to help make the process less error prone. I only uncovered the problem in troubleshooting a failed container build in a higher level work flow. This is precisely a case in point of the kind of errors users can and do encounter in deployment pipelines; we would like to make these higher level use cases more resilient. Thanks!

**Comment by yingcanw** [comment]
In fact, I still can't locate the issue you encountered, as I provided the compilation steps before, in the v3.3.1 version can not reproduce your error, if r21.11 can not be built normally, it may be related to the update of triton in your docker container(https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-triton). Maybe you can try a more stable version here, such as r21.09.  
In addition, all external components have been pre-compiled and installed in the Merlin container (https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/dockerfile.tri#L205-L218). The macro version is  backward compatible with Triton, please make sure that the corresponding version is also correctly installed in your operating environment.
