### ISSUE TITLE
HugeCTR model on sagemaker endpoint with Hierarchical Parameter Serve

### ISSUE THREAD

**Issue by andompesta** [triton-inference-server/hugectr_backend#55]
Hi all,

I'm looking to train a deploy a HugeCTR model. The model is a shallow model mostly based on user-item embeddings. I have about  180K users and 8K items.
I'm not interested in updating these embeddings, thus I'm not looking for the kafka component, but I'm looking for the ability of swapping embeddings from the GPUs cache to the CPU cache to reduce latency. Is this part of the Hierarchical Parameter Serve or is natively supported by any HugeCTR model?

**Comment by yingcanw** [comment]
@andompesta The Hierarchical Parameter Server(HPS) is a framework for embedding vectors lookup on large-scale embedding tables that was designed to effectively use GPU memory to accelerate the lookup by decoupling the embedding tables and **embedding cache** from the end-to-end inference pipeline of the deep recommendation model.  
The model trained by native HugeCTR or Tensorflow can be accelerated by native HPS or [HPS TF Plugin](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_tf_user_guide.html)  for embedding lookup.
For more details, you can refer to [Hierarchical Parameter Server Architecture](https://github.com/triton-inference-server/hugectr_backend/blob/main/hps_backend/docs/architecture.md#hugectr-inference-framework) and  [paper ](https://arxiv.org/pdf/2210.08804.pdf) from RecSys22.
